
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VPaned vpaned1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView _txtTexto;
	private global::Gtk.Button _btOpen;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vpaned1 = new global::Gtk.VPaned ();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 394;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this._txtTexto = new global::Gtk.TextView ();
		this._txtTexto.Buffer.Text = "vcxvxx";
		this._txtTexto.CanFocus = true;
		this._txtTexto.Name = "_txtTexto";
		this.GtkScrolledWindow.Add (this._txtTexto);
		this.vpaned1.Add (this.GtkScrolledWindow);
		global::Gtk.Paned.PanedChild w2 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.GtkScrolledWindow]));
		w2.Resize = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this._btOpen = new global::Gtk.Button ();
		this._btOpen.CanFocus = true;
		this._btOpen.Name = "_btOpen";
		this._btOpen.UseUnderline = true;
		this._btOpen.Label = global::Mono.Unix.Catalog.GetString ("open");
		this.vpaned1.Add (this._btOpen);
		global::Gtk.Paned.PanedChild w3 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this._btOpen]));
		w3.Shrink = false;
		this.Add (this.vpaned1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 688;
		this.DefaultHeight = 484;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
